#include "Electronics.h" 

#define OMEGA_CALIBRATION 1 / 360;
#define STEERING_ANGLE_CALIBRATION 1;
#define DRIVER_INPUT_CALIBRATION 1 / 4095;
#define VOLTAGE_CALIBRATION 1;
#define ANGLE_CALIBRATION 1;
#define ROTATION_CALIBRATION 1;
#define ACCELERATION_CALIBRATION 1;
#define CURRENT_CALIBRATION 1;
#define SHOCK_CALIBRATION 1 / 1000;

void TV_pp(ExtU* rtU);