#include "Electronics.h" 

#define OMEGA_CALIBRATION 1.0 / 360.0;
#define STEERING_ANGLE_CALIBRATION 0.1;
#define DRIVER_INPUT_CALIBRATION 1.0 / 4095.0;
#define VOLTAGE_CALIBRATION 1;
#define ANGLE_CALIBRATION 1;
#define ROTATION_CALIBRATION 1;
#define ACCELERATION_CALIBRATION 1;
#define CURRENT_CALIBRATION 1;
#define SHOCK_CALIBRATION 1.0 / 1000.0;

void TV_pp(ExtU* rtU);